# Generated by Django 4.1.2 on 2022-10-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User_data",
            fields=[
                ("CustomerId", models.AutoField(primary_key=True, serialize=False)),
                ("Age", models.IntegerField()),
                ("Location", models.CharField(max_length=100)),
                ("Device", models.CharField(max_length=100)),
                ("Income", models.IntegerField()),
                ("Balance", models.IntegerField()),
                ("Products", models.CharField(max_length=100)),
            ],
        ),
    ]
